name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: testing github actions
        run: pwd

      - name: testing printing
        run: echo "mahmoud"

      - uses : actions/checkout@v3 
      - name: "after"
        run: ls 
      - name: "login to dockerhub"
        run: docker login --username ${{secrets.DOCKERUSERNAME}}  --password ${{secrets.DOCKERTOKEN}}
      - name: "building image " 
        run: docker build -t ${{secrets.DOCKERUSERNAME}}/mahmoudgalal_2023040383 .
      - name: "pushing to dockerhub " 
        run: docker push ${{secrets.DOCKERUSERNAME}}/mahmoudgalal_2023040383